import Container from "./../../components/Container"
export default function AboutUs() {
  return <Container>
    <>
      <h1>O nas</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ac lacus rhoncus, mollis ligula vel, eleifend dolor. Praesent molestie sapien in massa iaculis, eget feugiat turpis rutrum. Vivamus convallis, justo eget varius facilisis, purus metus sodales sem, sed iaculis nisl magna a leo. Vivamus ultrices eros augue, ac commodo nunc pulvinar at. Integer fermentum at metus in dictum. Donec egestas placerat aliquam. Nunc laoreet scelerisque velit, eget posuere orci dignissim ac. Etiam porttitor urna vitae sapien scelerisque bibendum. Mauris non viverra velit, vitae elementum libero. Suspendisse lacinia ornare ligula gravida blandit. Nulla quis vehicula leo, tincidunt placerat lorem. Aenean dui erat, vestibulum dictum erat eu, sollicitudin pretium ante. Morbi at aliquam leo. Sed nisi leo, feugiat vel eros ac, convallis bibendum dui. Pellentesque ipsum turpis, faucibus vel tempor non, pharetra non lorem. Proin vitae libero et ex sagittis tempus eu eget nulla. Integer sed diam sollicitudin, ultrices velit sit amet, fermentum tellus. Nam arcu quam, suscipit vel bibendum nec, elementum tempor nulla. Maecenas tristique imperdiet dolor non elementum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vestibulum sit amet metus id condimentum. Maecenas aliquam dictum malesuada. Nullam interdum orci sit amet nulla convallis, in tincidunt erat vehicula. Fusce facilisis tincidunt hendrerit. Fusce eu velit interdum, efficitur felis mattis, rhoncus tortor. Phasellus fringilla faucibus orci, eu lobortis nulla. Suspendisse ac leo id nisl varius vulputate. Vivamus iaculis arcu a ex dapibus venenatis quis quis purus. Donec sagittis suscipit pretium. Mauris diam sapien, efficitur sit amet vestibulum vel, cursus consequat eros. Vestibulum iaculis id elit ac maximus. Maecenas ex ante, tempor quis metus at, molestie convallis mauris. Vivamus faucibus nibh sed tristique cursus. Ut eget odio a eros aliquam accumsan. Aliquam ac nulla vel quam semper posuere ac eu lacus. Duis blandit nibh quis diam ornare, at cursus sem tempor. Phasellus nibh mauris, lobortis tincidunt pharetra quis, eleifend nec orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque nec ornare dui, vitae ultrices nibh. Nulla facilisi. Integer semper libero eget velit interdum egestas. Cras interdum viverra libero, a tincidunt felis suscipit pretium. In sagittis justo. </p>
      <h2>Nagłówek drugiego stopnia o dowolnej treści</h2>
      <p>


        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget venenatis ante, sit amet rhoncus risus. Cras aliquam fermentum urna eu tincidunt. Nam tempor pretium fringilla. Morbi lacinia quam non eros venenatis egestas. Vivamus tincidunt felis id tortor luctus congue. Quisque id magna dui. Morbi rhoncus ac orci sit amet dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse potenti. Phasellus mollis eros nisi, id maximus mauris mollis ut. Cras egestas a ipsum id porttitor. Duis neque ex, cursus vitae sapien eu, venenatis eleifend dolor. Nam rhoncus, tellus vehicula elementum convallis, turpis arcu varius quam, eget lobortis tortor augue vel massa.

        Duis urna urna, pulvinar id posuere tempus, vehicula vitae urna. Etiam sit amet libero tellus. Phasellus varius massa metus, laoreet ullamcorper neque varius vitae. Phasellus ultrices turpis vel tellus cursus bibendum. Nam ut sagittis nunc, a pellentesque elit. Integer quis pharetra velit. Vivamus varius magna in placerat finibus. Duis vitae placerat purus.

        Maecenas quis turpis interdum, molestie ex malesuada, posuere velit. Nulla mollis ex quis tellus commodo pellentesque. Sed eget ornare elit, eget ullamcorper lorem. Pellentesque volutpat molestie justo ac aliquam. In ornare turpis leo, ut feugiat ipsum auctor quis. Phasellus pretium velit a sapien suscipit tempor. Cras egestas nunc magna, in hendrerit tortor mollis sit amet. Nulla vitae imperdiet mauris, sit amet lobortis sem. Praesent rhoncus erat ut sodales aliquam. Etiam imperdiet feugiat eros non molestie. Sed sit amet porttitor quam. In porttitor, sem pulvinar semper luctus, mi nulla facilisis mi, id rutrum massa lacus.
      </p>
    </>

  </Container>
}